title: Wacey Pruit
author:
  name: Wacey Pruit
  email: 'wacey@waceypruit.com'
blog:
  route: ''
metadata:
    description: 'Escape The Pod - Build Your Empire'
taxonomies: [category,tag,month]
# redirects:
#     /changelog: /blog/the-urban-jungle
# routes:
#     /something/else: /blog/focus-and-blur
#     /another/one/(.*): /blog/$1

